stages:
    - build
    - deploy

cache:
    # Cache per branch
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - .flatpak-builder/downloads/
        - .flatpak-builder/git/

build:
    stage: build
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.36'
    script:
        - make update export
    artifacts:
        paths:
            - "proton.flatpak"
        expire_in: 30 days
